AWSTemplateFormatVersion: "2010-09-09"
Description: "Creates an S3 bucket with CI/CD"
Parameters:
    Environment:
        Type: String
        Description: "The environment name"
    BucketName:
        Type: String
        Description: "The bucket name"
Resources:
     S3Bucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Ref BucketName
            Tags:
                 - Value: !Ref Environment
                   Key: Environment
