name: "Delete stack on merge"
on:
    pull_request:
        types: [closed]
        branches:
            - main
jobs:
    run-on-merge:
        if: ${{ github.event.pull_request.merged == true }}
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v3
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1

            - name: Get PR number
              run: echo "The PR number is ${{ github.event.pull_request.number }}"

            - name: Delete stack
              run: |
                  stack_name="pr-test-stack-${{ github.event.pull_request.number }}"
                  aws cloudformation delete-stack --stack-name $stack_name
